version: '3.8'

services:
  modelseed-ui:
    build:
      context: .
      args:
        - NEXT_PUBLIC_GIT_VERSION=${NEXT_PUBLIC_GIT_VERSION}
        - NEXT_PUBLIC_GIT_COMMIT=${NEXT_PUBLIC_GIT_COMMIT}
        - NEXT_PUBLIC_GIT_BRANCH=${NEXT_PUBLIC_GIT_BRANCH}
        - NEXT_PUBLIC_DEPLOY_DATE=${NEXT_PUBLIC_DEPLOY_DATE}
        - NEXT_PUBLIC_MODELSEED_API_URL=https://staging.modelseed.org/PMS/
        - NEXT_PUBLIC_USE_MODELSEED_API=true
        - NEXT_PUBLIC_USE_NEW_PROXY=true
    container_name: modelseed_ui
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_MODELSEED_API_URL=https://staging.modelseed.org/PMS/
      - NEXT_PUBLIC_USE_MODELSEED_API=true
      - NEXT_PUBLIC_USE_NEW_PROXY=true
